# Generated by Django 3.2.7 on 2021-10-22 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BouquetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('photo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=256)),
                ('photo_link', models.URLField()),
                ('creation_date', models.DateField()),
                ('sold_bouquets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('earnings', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bouquet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowers_marketplace.bouquetmodel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_marketplace.customermodel')),
            ],
        ),
        migrations.AddField(
            model_name='bouquetmodel',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers_marketplace.sellermodel'),
        ),
    ]
